env:
  global:
    - GH_REF: github.com/exp-team/exp-team.github.io.git
    - secure: "wYcYLZpOT6q1FCf/sfdKhzB5k4JshWaHzW607z2XTB7WUU0ValTh8RNSkK63tNsFDpMlResmFSlR+g0Bt8UNLe5sb8wIXtSRc44TO3r4nh9uvSDdfbTZs7fd31JTU7N46lhJ643EY4us0syQCtNHiOJ4Tvbwl7g6vlQPx9xgJMyvtGkak8C2NEA34i94CbI9Erp93rv+cLjTNmOa5q/i18Kt4e67acGDSOmkSbrUuS0GywlFA5YK0QTGtrV8J8gwWgU8yeUmtXGqjs6tSnf1sO+sP7DzBQ82k4t9fPAeyH6KLuNiP9dceTOFFK+dYESuf5aMb6KdPsG+r4EUaXzjReKSAZLRdnsEI5UJa+0WysAQxy6NQ9GE4PXAb9vayfShFK5tVHQ+EcQSVfvzWOIeYrMlECEtVFbBi5OfUKvWRTXuNcdBWJZGsz00LbkwTElIW0kYm+3x3sVmXFAjMRk0YkpLDYSO0sWWcd9grz+aQHeovlApmae1FAOEWzbbFkTMkKZvOQjN66Qjwb6hCa5R/x/esdF7UPekxgyvldh0HaUGl00PZRdSPcIews9ftR/zxGctX1agNQbpbJOryMB/iEGLRzlXJziTt2bdHy/k0NddgPTNr2kc9k8Ypk/Yyecd8oLEtJrQo/BjV2IL+6TmJyw7iGIQjfzkGMrHb73dwK4="

# S: Build Lifecycle
install:
  - npm install

before_script:
  - npm install -g hexo-cli@1.0.2

script:
  - hexo generate

after_script:
  - cd public
  - git init
  - git config user.name "yanhaijing"
  - git config user.email "yanhaijing@yeah.net"
  - git add .
  - git commit -m "travis-ci auto update"
  - git push -f "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle
